{
 "title": "Elixir Validator",
 "tags": [
  "elixir",
  "validator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Elixir Instance", "query": "elixir-testnet-1:8086" }
  ]
 },
 "panels": [
  { "title": "Validator metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Data Frames Processed",
   "type": "stat",
   "description": "Total number of data frames processed for each trading pair.\n\nPerformance Monitoring: Indicates the node's throughput for different assets.\nMarket Activity: Higher numbers may reflect more active markets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(data_frames_processed_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Proposal Requests and Responses",
   "type": "timeseries",
   "description": "Requests Sent: Number of proposal requests initiated by the node.\nResponses Received: Number of proposal responses received.\n\nConsensus Participation: Reflects the node's involvement in proposing and validating blocks.\nNetwork Health: A mismatch between requests and responses may indicate communication issues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "proposal_requests_sent_total{instance=\"$instance\"}",
     "legendFormat": "Requests Sent"
    },
    {
     "expr": "proposal_responses_received_total{instance=\"$instance\"}",
     "legendFormat": "Responses Received"
    }
   ]
  },
  {
   "title": "Strategy Executions",
   "type": "timeseries",
   "description": "Total number of strategy executions performed by the node.\n\nOperational Efficiency: Indicates how actively the node is applying strategies.\nAlgorithm Performance: Useful for evaluating the effectiveness of automated strategies.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "strategy_executions_total{instance=\"$instance\"}",
     "legendFormat": "Strategy executions"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "timeseries",
   "description": "This metric records the total number of errors encountered by the node. Errors could stem from failed transactions, network issues, or software bugs.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "error_count_total{instance=\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Uptime Percentage",
   "type": "timeseries",
   "description": "Measures the percentage of time the node has remained operational and connected to the network.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "uptime_percentage{instance=\"$instance\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Authorization Request Sent",
   "type": "timeseries",
   "description": "Number of authorization requests sent, possibly for secure communications or resource access.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "authorization_requests_sent_total{instance=\"$instance\"}",
     "legendFormat": "Request Count"
    }
   ]
  },
  { "title": "Increases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Rate of Total Data Frames Processed",
   "type": "timeseries",
   "description": "Rate of Total number of data frames processed for each trading pair.\n\nPerformance Monitoring: Indicates the node's throughput for different assets.\nMarket Activity: Higher numbers may reflect more active markets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "300 / sum(delta(data_frames_processed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Processing Rate Factor (5m Delta)"
    }
   ]
  },
  {
   "title": "Rate of Proposal Requests and Responses",
   "type": "timeseries",
   "description": "Requests Sent: Rate of proposal requests initiated by the node.\nResponses Received: Rate of Number of proposal responses received.\n\nConsensus Participation: Reflects the node's involvement in proposing and validating blocks.\nNetwork Health: A mismatch between requests and responses may indicate communication issues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "300 / sum(delta(proposal_requests_sent_total{instance=\"$instance\"}[5m])) \n",
     "legendFormat": "Request Rate (5m Delta)"
    },
    {
     "expr": "300 / sum(delta(proposal_responses_received_total{instance=\"$instance\"}[5m]))\n",
     "legendFormat": "Response Rate (5m Delta)"
    }
   ]
  },
  {
   "title": "Rate of Strategy executions",
   "type": "timeseries",
   "description": "Total number of strategy executions performed by the node.\n\nPerformance Monitoring: Indicates the node's throughput for different assets.\nMarket Activity: Higher numbers may reflect more active markets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "300 / delta(strategy_executions_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Strategy execution Rate Factor (5m Delta)"
    }
   ]
  },
  {
   "title": "Rate of Authorization Request",
   "type": "timeseries",
   "description": "Rate of authorization requests sent, possibly for secure communications or resource access.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": " 300 / delta(authorization_requests_sent_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Authorization Request Rate (5m Delta)"
    }
   ]
  }
 ]
}